# 项目信息
project:
  version: v1.0.0
  env: DEV

# 服务器配置
server:
  port: 9100

# Spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&autoR
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    ## 默认日期格式化
    date-format: yyyy-MM-dd HH:mm
  servlet:
    multipart:
      max-file-size: 5120000
      max-request-size: 5120000
  # redis 配置
  redis:
    host: 119.23.74.61
    port: 6379
    password: qwer@$..
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 0
  # rabbitmq 配置
  rabbitmq:
    host: 119.23.74.61
    port: 5672
    username: guest
    password: guest
    # 开启confirms回调 P -> Exchange
    publisher-confirms: true
    # 开启returnedMessage回调 Exchange -> Queue
    publisher-returns: true
    # 设置手动确认(ack) Queue -> C
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  # mail 配置
  mail:
    host: smtp.163.com
    username: kyriecao@163.com
    password: czp1314
    from: kyriecao@163.com
    properties:
      mail:
        smtp:
          starttls:
            required: true
            enable: true


# MyBatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml #对应mappers映射xml文件的所在路径
  configuration:
    map-underscore-to-camel-case: true # 使用resultType时自动将下划线转为驼峰命名

# logback信息配置
logback:
  level: INFO
  appender: ${project.env}

# dao层的日志设置为debug，方便查看sql
logging:
  level:
    com.tz.dao: debug

# Swagger配置
swagger:
  host:
  title: Project Swagger
  description:
  disabled: false # 是否禁用swagger
  redirect-uri: / # 禁用swagger时的重定向地址